### ISSUE TITLE
Fails when extensions already installed 

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-project-template#50]
## Describe the bug
The Azure DevOps sub-generator is failing if the extensions are installed in the organisation. Initially it complaint about gittools.gittools, I uninstalled and run again, Now it is erroring for sariftools.sarif-viewer-build-tab. I hope it works even if the extension are installed in the organisation. Just checking what is the case at your end, not sure if there is any problem at my side.

## To reproduce
Run Azure DevOps generator with any of the extensions already installed. 

## Expected behaviour
Extensions are not to be installed if they are already installed.

## Screenshots
```
Creating pipelines/azure-pipelines-pull-request.yml build...
Creating pipelines/azure-pipelines.yml build...
Extension: PowerPlatform-BuildTools is already installed.
Extension: sarif-viewer-build-tab is already installed.
Extension: gittools is already installed.
Installing 'PowerPlatform-BuildTools' from 'microsoft-IsvExpTools' extension...
Installing 'sarif-viewer-build-tab' from 'sariftools' extension...
Installing 'gittools' from 'gittools' extension...
Package generator encountered an error.
```
```
Error: TF1590010: Extension gittools.gittools is already installed in this organization.
at RestClient.<anonymous> (C:\Users\satkar\AppData\Roaming\npm\node_modules\@capgeminiuk\generator-powerapps-project\node_modules\typed-rest-client\RestClient.js:200:31)
at Generator.next (<anonymous>)
at fulfilled (C:\Users\satkar\AppData\Roaming\npm\node_modules\@capgeminiuk\generator-powerapps-project\node_modules\typed-rest-client\RestClient.js:6:58)
at processTicksAndRejections (internal/process/task_queues.js:93:5) {
statusCode: 409,
result: {
'$id': '1',
innerException: null,
message: 'TF1590010: Extension gittools.gittools is already installed in this organization.',
typeName: 'Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.ExtensionAlreadyInstalledException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi',
typeKey: 'ExtensionAlreadyInstalledException',
errorCode: 0,
eventId: 3000
}
}
```

## Environment (please complete the following information):
 - yo version
 - generator-powerapps-project version
 - Power Apps CLI version
 - Power Apps environment version

## Additional context
_Add any other context about the problem here._

**Comment by tdashworth** [comment]
@satyarkar created this issue for tracking.

**Comment by tdashworth** [comment]
@satyarkar I found the issue - not sure how this regressed.
