### ISSUE TITLE
Fails to create Service Connection

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-project-template#51]
## Describe the bug
When running the Azure DevOps generator, it fails with the below error.

## To reproduce
Run the Azure DevOps generator. 

## Expected behaviour
Service Connection to be created.

## Screenshots
```
Error: Unable to find service connection type 'powerplatform-spn' using authentication scheme 'None'.
    at RestClient.<anonymous> (C:\code\capgemini\powerapps-project-template\node_modules\typed-rest-client\RestClient.js:200:31)
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\capgemini\powerapps-project-template\node_modules\typed-rest-client\RestClient.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  statusCode: 400,
  result: {
    '$id': '1',
    innerException: null,
    message: "Unable to find service connection type 'powerplatform-spn' using authentication scheme 'None'.",
    typeName: 'Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi.ServiceEndpointException, Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi',
    typeKey: 'ServiceEndpointException',
    errorCode: 0,
    eventId: 3000
  }
}
```

## Environment (please complete the following information):
 - yo version
 - generator-powerapps-project version
 - Power Apps CLI version
 - Power Apps environment version

## Additional context
_Add any other context about the problem here._

**Comment by tdashworth** [comment]
This was because the extension installation (microsoft-IsvExpTools.PowerPlatform-BuildTools) was still ongoing. Some wait time needs to be added after the installation.
