### ISSUE TITLE
Repo didn't roll back

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-project-template#8]
When running the Azure DevOps generator, when an error occurs, the repo fails to roll back. So is because of the below issue: 

```
    TypeError: Cannot read property 'rmdir' of undefined
    at RepoGenerator.rollback (C:\Users\***\Documents\Projects\alm-labs\powerapps-project-template\generators\azuredevops\generator\RepoGenerator.js:32:29)
    at process._tickCallback (internal/process/next_tick.js:178:7)

```

**Comment by tdashworth** [comment]
Fixed by #58
